In [1]:
import pandas as pd
import csv
import glob

In [2]:
df = pd.concat([pd.read_csv(f) for f in glob.glob('C:/Users/20213338/Documents/uni/Jaar2/Q4/DC 2/data_2010_to_2023/'+'*.csv')])
df

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.145949,51.593914,On or near Providence Place,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
1,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.140192,51.582311,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
2,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
3,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
4,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
92828,9e2cf8a9d0d86bb4f87e7d5828ff37fb3d4e8cb855e327...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
92829,cea2e7ccaa5c3bcf1ea20fbd4444831a7b8d0169872524...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Local resolution,NaN
92830,cb35cc774e0d827d343f949f41068d4fc89bb81074a506...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
92831,1ed02666b90806fd9b57f771aaf55ef81708f095ab8605...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
92832,7a43685bfa1543e796c96d81b22436eab79432b5e3f46a...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN

In [3]:
df_burglary = df[df['Crime type'] == 'Burglary']
df_burglary = df_burglary.reset_index(drop = True)
df_burglary

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.140619,51.583427,On or near Rams Grove,E01000027,Barking and Dagenham 001A,Burglary,NaN,NaN
1,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.128479,51.583414,On or near Cavalier Close,E01000028,Barking and Dagenham 001B,Burglary,NaN,NaN
2,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.134801,51.578470,On or near Portland Close,E01000029,Barking and Dagenham 001C,Burglary,NaN,NaN
3,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.131156,51.582323,On or near Lake Road,E01000029,Barking and Dagenham 001C,Burglary,NaN,NaN
4,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,0.140466,51.584159,On or near Bagleys Spring,E01000030,Barking and Dagenham 001D,Burglary,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
919927,400f7419cc445a8de4b2140c3153d63d99358e69aa77a9...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Burglary,Under investigation,NaN
919928,dd317e1582794d8f24562a1bde1024129a7466cb2f3993...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Burglary,Under investigation,NaN
919929,9974a1809c3da57ba717f92911e62c86b590c92d0469c2...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Burglary,Under investigation,NaN
919930,e2483074dc8848d0823d61711e9f18d8cb33f05ca4b1d9...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Burglary,Under investigation,NaN
919931,6947ac864b02c1b3ad979845b7d37c69d0ab236a6fdee2...,2023-03,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Burglary,Under investigation,NaN

In [4]:
df_burglary.dropna(subset = ['LSOA name','LSOA code'], inplace=True)

In [5]:

df_barnet = df_burglary.loc[df_burglary['LSOA name'].str.contains("Barnet", case=False)]
df_barnet
df_barnet = df_barnet.reset_index(drop = True)
df_barnet
df_barnet.to_csv('df_combined.csv')