In [1]:
import pandas as pd
import csv
import glob

In [2]:
#opens the dataframe of burglaries from 2010 till 2023
df_original = pd.read_csv('df_combined.csv')
df_original.drop('Unnamed: 0', axis = 1)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.201877,51.655538,On or near High Street,E01000248,Barnet 001A,Burglary,NaN,NaN
1,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.207853,51.654317,On or near The Avenue,E01000248,Barnet 001A,Burglary,NaN,NaN
2,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.202510,51.656348,On or near Bruce Road,E01000248,Barnet 001A,Burglary,NaN,NaN
3,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.206779,51.654768,On or near The Drive,E01000248,Barnet 001A,Burglary,NaN,NaN
4,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.209537,51.655223,On or near Marriott Road,E01000249,Barnet 001B,Burglary,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
44133,fda0870be993d2c9352ae14a540bf529c15a7aa9d92a4e...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.202163,51.559100,On or near Hocroft Road,E01000139,Barnet 041B,Burglary,Under investigation,NaN
44134,c6c2d9a772695865f4ca33fce59c26c48fe3a1cdac8c22...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.202163,51.559100,On or near Hocroft Road,E01000139,Barnet 041B,Burglary,Under investigation,NaN
44135,e5bab2bd4f31de44515dbf125b85284392d0349139a1d3...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.197843,51.561093,On or near Church Walk,E01000140,Barnet 041C,Burglary,Under investigation,NaN
44136,823465427f8764e250a48312715a4bd87e8012412046c6...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.199449,51.563896,On or near Llanelly Road,E01000140,Barnet 041C,Burglary,Under investigation,NaN
44137,50b5bbf4987109ee189f8a736ec7e92365b25169b7f783...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.197843,51.561093,On or near Church Walk,E01000140,Barnet 041C,Burglary,Under investigation,NaN

In [3]:
# opens a dataframe where you have all the information of the LSOA's and to which wards they belong. 

df_t = pd.read_csv('Area_(2021)_to_Ward_(2022).csv')
df_LSOA21NM = df_t.loc[df_t['LSOA21NM'].str.contains("Barnet", case=False)]
df_LSOA21NM

# did some test and the wards align with the readings

df = df_LSOA21NM.reset_index(drop = True)
df

,LSOA21CD,LSOA21NM,LSOA21NMW,WD22CD,WD22NM,WD22NMW,LAD22CD,LAD22NM,LAD22NMW,ObjectId
0,E01000145,Barnet 037A,NaN,E05013631,Childs Hill,NaN,E09000003,Barnet,NaN,28801
1,E01000140,Barnet 041C,NaN,E05013631,Childs Hill,NaN,E09000003,Barnet,NaN,28804
2,E01000136,Barnet 038B,NaN,E05013631,Childs Hill,NaN,E09000003,Barnet,NaN,28807
3,E01000189,Barnet 014D,NaN,E05013637,Edgware,NaN,E09000003,Barnet,NaN,28810
4,E01000151,Barnet 026B,NaN,E05013632,Colindale North,NaN,E09000003,Barnet,NaN,28812
...,...,...,...,...,...,...,...,...,...,...
215,E01000315,Barnet 022F,NaN,E05013651,Woodhouse,NaN,E09000003,Barnet,NaN,29432
216,E01000321,Barnet 012E,NaN,E05013651,Woodhouse,NaN,E09000003,Barnet,NaN,29433
217,E01000320,Barnet 011D,NaN,E05013651,Woodhouse,NaN,E09000003,Barnet,NaN,29434
218,E01000318,Barnet 019E,NaN,E05013651,Woodhouse,NaN,E09000003,Barnet,NaN,29435
219,E01000323,Barnet 019F,NaN,E05013651,Woodhouse,NaN,E09000003,Barnet,NaN,29436

In [4]:
# makes a dictionary where every LSOA is a key and the ward of the LSOA is the value
dct_LSOA_to_WARD = {}
for index, row in df.iterrows():
    key = row['LSOA21CD']
    value = df["WD22NM"][index]
    dct_LSOA_to_WARD[key] = value
dct_LSOA_to_WARD

{'E01000145': 'Childs Hill',
 'E01000140': 'Childs Hill',
 'E01000136': 'Childs Hill',
 'E01000189': 'Edgware',
 'E01000151': 'Colindale North',
 'E01000232': 'Edgware',
 'E01033916': 'Colindale North',
 'E01000234': 'Edgware',
 'E01000154': 'Colindale North',
 'E01000271': 'Barnet Vale',
 'E01000268': 'Barnet Vale',
 'E01000247': 'Barnet Vale',
 'E01000251': 'Barnet Vale',
 'E01000288': 'Barnet Vale',
 'E01000246': 'Barnet Vale',
 'E01000267': 'Barnet Vale',
 'E01000252': 'Barnet Vale',
 'E01000270': 'Barnet Vale',
 'E01000269': 'Barnet Vale',
 'E01000120': 'Brunswick Park',
 'E01000123': 'Brunswick Park',
 'E01000117': 'Brunswick Park',
 'E01000124': 'Brunswick Park',
 'E01000118': 'Brunswick Park',
 'E01000115': 'Brunswick Park',
 'E01000119': 'Brunswick Park',
 'E01000121': 'Brunswick Park',
 'E01000116': 'Brunswick Park',
 'E01000122': 'Brunswick Park',
 'E01000133': 'Burnt Oak',
 'E01000127': 'Burnt Oak',
 'E01000226': 'Burnt Oak',
 'E01000134': 'Burnt Oak',
 'E01000235': 'Burnt Oak',
 'E01000131': 'Burnt Oak',
 'E01033913': 'Burnt Oak',
 'E01000128': 'Burnt Oak',
 'E01000194': 'Burnt Oak',
 'E01000130': 'Burnt Oak',
 'E01033914': 'Burnt Oak',
 'E01000129': 'Burnt Oak',
 'E01000132': 'Burnt Oak',
 'E01000139': 'Childs Hill',
 'E01000144': 'Childs Hill',
 'E01000138': 'Childs Hill',
 'E01000146': 'Childs Hill',
 'E01000137': 'Childs Hill',
 'E01000135': 'Childs Hill',
 'E01000142': 'Childs Hill',
 'E01000214': 'Childs Hill',
 'E01000126': 'Colindale North',
 'E01000152': 'Colindale North',
 'E01000153': 'Colindale North',
 'E01033917': 'Colindale South',
 'E01000147': 'Colindale South',
 'E01033920': 'Colindale South',
 'E01033919': 'Colindale South',
 'E01033921': 'Colindale South',
 'E01033915': 'Colindale South',
 'E01033925': 'Colindale South',
 'E01033922': 'Colindale South',
 'E01033918': 'Colindale South',
 'E01033924': 'Colindale South',
 'E01033923': 'Colindale South',
 'E01000223': 'Cricklewood',
 'E01000224': 'Cricklewood',
 'E01000143': 'Cricklewood',
 'E01000222': 'Cricklewood',
 'E01000221': 'Cricklewood',
 'E01000141': 'Cricklewood',
 'E01000173': 'East Barnet',
 'E01000174': 'East Barnet',
 'E01000175': 'East Barnet',
 'E01000168': 'East Barnet',
 'E01000171': 'East Barnet',
 'E01000167': 'East Barnet',
 'E01000172': 'East Barnet',
 'E01000166': 'East Barnet',
 'E01000169': 'East Barnet',
 'E01000170': 'East Barnet',
 'E01000181': 'East Finchley',
 'E01000180': 'East Finchley',
 'E01000176': 'East Finchley',
 'E01000178': 'East Finchley',
 'E01000185': 'East Finchley',
 'E01000184': 'East Finchley',
 'E01000179': 'East Finchley',
 'E01000183': 'East Finchley',
 'E01000177': 'East Finchley',
 'E01000182': 'East Finchley',
 'E01000193': 'Edgware',
 'E01000192': 'Edgware',
 'E01000233': 'Edgware',
 'E01000191': 'Edgware',
 'E01000190': 'Edgware',
 'E01000227': 'Edgware',
 'E01000195': 'Edgwarebury',
 'E01000186': 'Edgwarebury',
 'E01000229': 'Edgwarebury',
 'E01000231': 'Edgwarebury',
 'E01000230': 'Edgwarebury',
 'E01000188': 'Edgwarebury',
 'E01000187': 'Edgwarebury',
 'E01000228': 'Edgwarebury',
 'E01000197': 'Finchley Church End',
 'E01000304': 'Finchley Church End',
 'E01000198': 'Finchley Church End',
 'E01000202': 'Finchley Church End',
 'E01000199': 'Finchley Church End',
 'E01000204': 'Finchley Church End',
 'E01000200': 'Finchley Church End',
 'E01000196': 'Finchley Church End',
 'E01000201': 'Finchley Church End',
 'E01000203': 'Finchley Church End',
 'E01000160': 'Friern Barnet',
 'E01000164': 'Friern Barnet',
 'E01000265': 'Friern Barnet',
 'E01000163': 'Friern Barnet',
 'E01000158': 'Friern Barnet',
 'E01000162': 'Friern Barnet',
 'E01000165': 'Friern Barnet',
 'E01000159': 'Friern Barnet',
 'E01000156': 'Friern Barnet',
 'E01000157': 'Friern Barnet',
 'E01000161': 'Friern Barnet',
 'E01000206': 'Garden Suburb',
 'E01000213': 'Garden Suburb',
 'E01000210': 'Garden Suburb',
 'E01000207': 'Garden Suburb',
 'E01000205': 'Garden Suburb',
 'E01000209': 'Garden Suburb',
 'E01000208': 'Garden Suburb',
 'E01000225': 'Golders Green',
 'E01000219': 'Golders Green',
 'E01000216': 'Golders Green',
 'E01000217': 'Golders Green',
 'E01000218': 'Golders Green',
 'E01000211': 'Golders Green',
 'E01000220': 'Golders Green',
 'E01000215': 'Golders Green',
 'E01000212': 'Golders Green',
 'E01000316': 'West Finchley',
 'E01000303': 'West Finchley',
 'E01000297': 'West Finchley',
 'E01000244': 'Hendon',
 'E01000238': 'Hendon',
 'E01000236': 'Hendon',
 'E01000240': 'Hendon',
 'E01000319': 'West Finchley',
 'E01000311': 'Hendon',
 'E01000242': 'Hendon',
 'E01000239': 'Hendon',
 'E01000245': 'Hendon',
 'E01000241': 'Hendon',
 'E01000243': 'Hendon',
 'E01000237': 'Hendon',
 'E01000250': 'High Barnet',
 'E01000249': 'High Barnet',
 'E01000286': 'High Barnet',
 'E01000248': 'High Barnet',
 'E01000253': 'High Barnet',
 'E01000290': 'High Barnet',
 'E01000254': 'High Barnet',
 'E01000255': 'Mill Hill',
 'E01000258': 'Mill Hill',
 'E01000256': 'Mill Hill',
 'E01000260': 'Mill Hill',
 'E01000261': 'Mill Hill',
 'E01000263': 'Mill Hill',
 'E01033911': 'Mill Hill',
 'E01000259': 'Mill Hill',
 'E01000264': 'Mill Hill',
 'E01000275': 'Totteridge & Woodside',
 'E01000278': 'Totteridge & Woodside',
 'E01000279': 'Totteridge & Woodside',
 'E01033912': 'Totteridge & Woodside',
 'E01000283': 'Totteridge & Woodside',
 'E01000280': 'Totteridge & Woodside',
 'E01000257': 'Totteridge & Woodside',
 'E01000276': 'Totteridge & Woodside',
 'E01000277': 'Totteridge & Woodside',
 'E01000294': 'Underhill',
 'E01000291': 'Underhill',
 'E01000287': 'Underhill',
 'E01000285': 'Underhill',
 'E01000292': 'Underhill',
 'E01000289': 'Underhill',
 'E01000293': 'Underhill',
 'E01000295': 'West Finchley',
 'E01000302': 'West Finchley',
 'E01000296': 'West Finchley',
 'E01000301': 'West Finchley',
 'E01000299': 'West Finchley',
 'E01000317': 'West Finchley',
 'E01000300': 'West Finchley',
 'E01000298': 'West Finchley',
 'E01000309': 'West Hendon',
 'E01000312': 'West Hendon',
 'E01000310': 'West Hendon',
 'E01000306': 'West Hendon',
 'E01000313': 'West Hendon',
 'E01000308': 'West Hendon',
 'E01000150': 'West Hendon',
 'E01000307': 'West Hendon',
 'E01000305': 'West Hendon',
 'E01000314': 'West Hendon',
 'E01000274': 'Whetstone',
 'E01000284': 'Whetstone',
 'E01000281': 'Whetstone',
 'E01000282': 'Whetstone',
 'E01000266': 'Whetstone',
 'E01000273': 'Whetstone',
 'E01000272': 'Whetstone',
 'E01000324': 'Woodhouse',
 'E01000322': 'Woodhouse',
 'E01000315': 'Woodhouse',
 'E01000321': 'Woodhouse',
 'E01000320': 'Woodhouse',
 'E01000318': 'Woodhouse',
 'E01000323': 'Woodhouse'}

In [5]:
# appends a new column called ward to the df_original.
# it first looks at the LSOA code an looks that code up un the dictionary which gives the wards of the LSOA
# and it puts that ward in the ward column
lst_old = ['E01000262', 'E01000125', 'E01033572', 'E01000155', 'E01033573',
       'E01000148'] #the LSOA codes that are not in the 2021 form 
for index, row in df_original.iterrows():
    LSOA = row['LSOA code']
    if LSOA in lst_old: 
        df_original['ward'] = 0
    else:
        ward = dct_LSOA_to_WARD[LSOA] 
        df_original['ward'] = ward
        
df_original

,Unnamed: 0,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context,ward
0,0,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.201877,51.655538,On or near High Street,E01000248,Barnet 001A,Burglary,NaN,NaN,Childs Hill
1,1,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.207853,51.654317,On or near The Avenue,E01000248,Barnet 001A,Burglary,NaN,NaN,Childs Hill
2,2,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.202510,51.656348,On or near Bruce Road,E01000248,Barnet 001A,Burglary,NaN,NaN,Childs Hill
3,3,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.206779,51.654768,On or near The Drive,E01000248,Barnet 001A,Burglary,NaN,NaN,Childs Hill
4,4,NaN,2010-12,Metropolitan Police Service,Metropolitan Police Service,-0.209537,51.655223,On or near Marriott Road,E01000249,Barnet 001B,Burglary,NaN,NaN,Childs Hill
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44133,44133,fda0870be993d2c9352ae14a540bf529c15a7aa9d92a4e...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.202163,51.559100,On or near Hocroft Road,E01000139,Barnet 041B,Burglary,Under investigation,NaN,Childs Hill
44134,44134,c6c2d9a772695865f4ca33fce59c26c48fe3a1cdac8c22...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.202163,51.559100,On or near Hocroft Road,E01000139,Barnet 041B,Burglary,Under investigation,NaN,Childs Hill
44135,44135,e5bab2bd4f31de44515dbf125b85284392d0349139a1d3...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.197843,51.561093,On or near Church Walk,E01000140,Barnet 041C,Burglary,Under investigation,NaN,Childs Hill
44136,44136,823465427f8764e250a48312715a4bd87e8012412046c6...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.199449,51.563896,On or near Llanelly Road,E01000140,Barnet 041C,Burglary,Under investigation,NaN,Childs Hill
44137,44137,50b5bbf4987109ee189f8a736ec7e92365b25169b7f783...,2023-03,Metropolitan Police Service,Metropolitan Police Service,-0.197843,51.561093,On or near Church Walk,E01000140,Barnet 041C,Burglary,Under investigation,NaN,Childs Hill